const m7 = {
    id: 'm7', title: 'VII. Power Query, Power Pivot y VBA', level: 'god', icon: 'fa-solid fa-code',
    lessons: [
        { id: 'm7_l1', title: 'El Ecosistema Power', desc: 'Introducción Ineludible al Stack Developer', icon: 'fa-bolt', content: `<h3>No más Excel Básico de ratón</h3><p>Para manejar verdaderos volúmenes masivos de la industria hay 3 pilares supremos. <strong>Power Query</strong> para limpiar la mugre (ETL), <strong>Power Pivot</strong> (Modelado DAX in-memory) y <strong>VBA</strong> (Librerías de Macros nativos para tareas automatizadas Windows).</p>` },
        { id: 'm7_l2', title: 'Power Query Introducción', desc: 'Editor revolucionario de ETL oculto', icon: 'fa-broom', content: `<h3>Destruye Archivos Manualmente... Una sola Vez</h3><p>Datos > Obtener Datos (De Carpeta, CSV, Web, DB, SQL). PQ abre un canvas virtual separado. Aplicas transposición, tipos de Datos fijos y borrar basura apretando botones. 0 fórmulas. En el panel lateral derecho el Editor "Graba como película paso a paso" tus decisiones quirúrgicas.</p>` },
        { id: 'm7_l3', title: 'Anexar y Combinar en PQ', desc: 'El SQL Inner/Outer join de excel puro', icon: 'fa-link', content: `<h3>Adiós BuscarV</h3><p>En vez de poner fórmulas, desde PQ aplicas "Combinar Consultas". Si tu query A tiene ID Empleados, picas sobre "Combinar", eliges query B con Nóminas... Y escoges el tipo de unión Relacional. Se fusionan formando una Súper Tabla sin colapsar el C-Drive.</p>` },
        { id: 'm7_l4', title: 'Modificando Lenguaje "M"', desc: 'El motor interno funcional en bruto de PQ', icon: 'fa-file-code', content: `<h3>Más allá de la Interfaz</h3><p>En el Editor Inicial al picar Vista > Editor Avanzado verás bloques raros <code>let Fuente = Excel.Workbook, ... in Oculto</code>. El "M" es funcional lineal. Saber arreglar un simple nombre de columna en ese bloc de notas salva automatizaciones caídas enteras de un mes a otro.</p>` },
        { id: 'm7_l5', title: 'Modelado Relacional Power Pivot', desc: 'Destruyendo límite de las Máximas Filas', icon: 'fa-cubes', content: `<h3>Red de Araña</h3><p>La Tabla Dinámica colapsó la memoria a los 2 Millones? Habilita el COM Addin de Power Pivot. Mete tu Data al Data Model, entra a la "Vista de Diagrama" y simplemente Tira una raya uniendo Tu Fact_Table a tu Dim_Region. Sin fórmulas lentísimas.</p>` },
        { id: 'm7_l6', title: 'Fundamentos DAX Calculados', desc: 'El código puro financiero de PowerBI/Pivot', icon: 'fa-square-root-variable', content: `<h3>Columnas Calculadas vs Medidas</h3><p>NO crear <code>=Ingreso-Costo</code> como Columnas físicas de DAX estúpidamente de vuelta, pesa como piedra. Crea una MEDIDA DAX. Ejemplo: <code>Margen:=SUM(Tabla[Ingresos]) - SUM(Tabla[Costos])</code>, esa medida pesa CERO BYTES, y solo es procesada al meterla en valores de la Pivot.</p>` },
        { id: 'm7_l7', title: 'La Reina Suprema CALCULATE', desc: 'Manipulador Espacio Tiempo Dimensional Contextual', icon: 'fa-crown', content: `<h3>Filtrado Externo Modificado</h3><p>Calcula una Métrica DAX sin que le importe ser aplastada por Filtros del Menú. <code>=CALCULATE( SUM(Ventas), Region="Norte" )</code>. Ignora filtros de años e impone condiciones. Crucial para sacar % De Total de las Ventas sin errar.</p>` },
        { id: 'm7_l8', title: 'Macros Grabadora Ingenua', desc: 'La Inteligencia Artificial de 1999', icon: 'fa-video', content: `<h3>Imitando y repitiendote</h3><p>Para tareas súper planas: Programador > Grabar Macro. Excel documentará tus clics. Pinta la celda Roja y Pon "Completado". Detener. Creas un Botón y asocias Clic a Maco. Hará tu trabajo 1,000x veeces más veloz mecánicamente.</p>` },
        { id: 'm7_l9', title: 'Visual Basic Editor VBE', desc: 'Abriendo El Cerebro de la Matrix Core', icon: 'fa-terminal', content: `<h3>Alt + F11 - The Console Coder</h3><p>Entras al IDE (Menú Visual Basic). Insertar Módulo. Crear <code>Sub MasterClean() ... End Sub</code>. Aquí no arrastras el mouse. Escribes programando código imperativo VBA de verdad orientada a Objetos manipulables invisibles o visibles por ventanas.</p>` },
        { id: 'm7_l10', title: 'For Each Loop en VBA', desc: 'Ejecutando ciclos de CPU destructivos brutales', icon: 'fa-repeat', content: `<h3>The Power Iterate Pattern</h3><p>El poder puro. <code>For each Cel In Selection</code><br> <code>  If Cel.Value = "#N/A" Then</code><br><code>    Cel.Value = 0</code><br> <code>  End If</code><br><code>Next</code><br> Limpia miles de errores de reportes en loop iterativo a la velocidad parpadeante imperceptible para tu retina.</p>` }
    ]
};
